version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: recipes
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
